#! /bin/sh

spotify &
discord &
setxkbmap -layout gb,hu -option grp:alt_shift_toggle &

bspc monitor -d 1 2 3 4 5

. "${HOME}/.cache/wal/colors.sh"
bspc config normal_border_color "$color8"
bspc config focused_border_color "$color4"
~/.config/bspwm/scripts/singleton_border.sh "$color4" "$color8" &

bspc config border_width        3
bspc config window_gap		10

bspc config ignore_ewmh_focus true
bspc rule -a Spotify desktop=5
bspc rule -a discord desktop=3

