#! /bin/sh

bspc monitor -d 1 2 3 4 5

. "${HOME}/.cache/wal/colors.sh"
bspc config normal_border_color "$color8"
bspc config focused_border_color "$color4"
~/.config/bspwm/singleton_border.sh "$color4" "$color8" &

bspc config border_width        2
bspc config window_gap		10

bspc config ignore_ewmh_focus true
bspc rule -a Spotify desktop=5

