#! /bin/sh

# Start necessary programs
picom -fb &   			      # Compositor
xsetroot -cursor_name left_ptr &      # Cursor appearance
nitrogen --restore & 		      # Wallpaper
pgrep -x sxhkd > /dev/null || sxhkd & # Shortcut program
~/.config/polybar/launch.sh &         # Polybar
setxkbmap -layout gb,hu -option grp:alt_shift_toggle # Keyboard layout

bspc monitor -d 1 2 3 4 5

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

